version: '3.8'

services:
  db:
    image: postgres:15
    container_name: wallet-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: wallet_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - wallet-net

volumes:
  db_data:

networks:
  wallet-net:
    driver: bridge
