version: '3.8'

services:
  db:
    image: postgres:15
    container_name: wallet-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: wallet_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - wallet-net

  auth:
    build:
      context: ./services/auth
    container_name: wallet-auth
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://postgres:secret@db:5432/wallet_db
      - JWT_SECRET=supersecret
    networks:
      - wallet-net

  user:
    build:
      context: ./services/user
    container_name: wallet-user
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - PORT=8081
      - DATABASE_URL=postgres://postgres:secret@db:5432/wallet_db
    networks:
      - wallet-net

volumes:
  db_data:

networks:
  wallet-net:
    driver: bridge
